server:
  port: 8000

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost
#          - teahouse.beyond-coding.com
      bindings:
        teas:
          destination: teahouse.order.tea
          content-type: application/json
        desserts:
          destination: teahouse.order.dessert
          content-type: application/json
        products:
          destination: teahouse.product.ready
          content-type: application/json