server:
  port: 8002

name:
  expert: Riyad
  dessert: Strawberry pie
  teahouse: Some Teahouse

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost
#          - teahouse.beyond-coding.com
      bindings:
        orders:
          destination: teahouse.order.dessert
          content-type: application/json
          group: dessert-experts
        products:
          destination: teahouse.product.ready
          content-type: application/json