name:
  teahouse: Best Tea House

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - teahouse.beyond-coding.com
#          - localhost
      bindings:
        orders:
          destination: teahouse.order.tea
          content-type: application/json
          group: tea-experts
        products:
          destination: teahouse.product.ready
          content-type: application/json