spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - teahouse.beyond-coding.com
#          - localhost
      bindings:
        teas:
          destination: teahouse.order.tea
          content-type: application/json
        desserts:
          destination: teahouse.order.dessert
          content-type: application/json
        products:
          destination: teahouse.product.ready
          content-type: application/json