server:
  port: 8001

name:
  expert: Hosam
  tea: White tea
  teahouse: Some Teahouse

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost
#          - teahouse.beyond-coding.com
      bindings:
        orders:
          destination: teahouse.order.tea
          content-type: application/json
          group: tea-experts
        products:
          destination: teahouse.product.ready
          content-type: application/json